### ISSUE TITLE
Create sorting file for report (EPIC)

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#11]
`As the program, I want to be able to filter the list of rows within the user-specified radius which I will receive according to the user defined category of sorting, so that I can pass on a correctly sorted list of rows to the report saving module.`

This is made up of several parts:
 - [x] Sort by Distance algorithm (this is a simple numerical sorting exercise)
 - [x] Date (the only date data we get is month, so order by the month)
 - [x] Crime Category (we can ask python to sort alphabetically, google how to do this simply)
 - [x] No option, so we just pass the received data list on to the next module for report creation and saving.
 - [x] All need testing

A separate issue to be created for the creation of each algorithm and the overarching logic of the module.

**Comment by roksolana-15** [comment]
@FebruaryRain

**Comment by FebruaryRain** [comment]
Confirmed
