### ISSUE TITLE
Add User Input Validation Logic to prevent invalid user input (EPIC)

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#25]
`As the user, I only want to input valid characters in the input fields, so that the program will not fail and so I can get my reports`
`As the program, I want to limit the characters the user inputs so that I can only receive input I consider valid and so will not fail`

Relates to issue #17, #18, #24 
This issue call for logic that rejects invalid user input.
The simplest way to do this is to have input whitelisted to only alphanumeric chars.
This would call for a part of the code to: 
 - [ ] Assess user input
 - [ ] Test if it has characters which are non-alphanumeric
 - [ ] Return a boolean response which can be used to see if the user needs to re-input.

ISSUES:
 - If there are only alphanumeric chars allowed, that means there can never be any whitespaces.
  - Therefore, the User needs warning of this.
  - Further, the logic for looking up postcodes needs creating, as there is whitespace in the postcodes. Luckily, we can take advantage of:
    - All postcodes are 7 chars long. 
    - If the postcode is of format "EX1 0PL" (two numbers in the middle), we can simply split the list in two at the midpoint and create a new string to use
    - If the postcode is of format "EX116JT" (three numbers) the we need not split.
    - This can all be done by asking the user to input the string with no spaces, telling them to go again if there is one, then assessing the length of their return.

**Comment by FebruaryRain** [comment]
Across the various UI functions this is implemented in one way or another. I'll see what the appetite for fixing this better is like later.

**Comment by FebruaryRain** [comment]
On review, this is covered. Will close now as part of the project wind-down.
