### ISSUE TITLE
Test the geodist module provided

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#7]
`As a developer, I want to be confident that the geodist module we are provided with works OK, so that I can continue to use it with confidence`

We have a geodist module given to us. It will return the distance between two lat and long points and give the distance in metres. 
This needs testing according to the following note in the module from the lecturers:
```
# TODO: Please verify the function by providing suitable test cases and
# using asserts. The test should cover the cases your program is to deal
# with, e.g. do not verify the correct distance between New York and London
# For your testing allow a tolerance for the distance calculation as the
# calculation is an approximation.
```
 - [x] Create the tests from the data supplied
 - [x] Get the right answers from the internet (https://www.movable-type.co.uk/scripts/latlong.html)
 - [x] Test the module

**Comment by FebruaryRain** [comment]
Tested, answers look fine.
